#remote_theme: minima #pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Rachit's Catalogue

author: 
  name: Rachit Shankar
  email: rachitshankar@gmail.com

description: > 
  A peronsnal site to keep track of thoughts and evolve them as I learn more things.

theme: minima
# remote_theme: jekyll/minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# link only to specific pages in the header 
header_pages:
  - index.md
  - about.md

minima: 
  skin: auto

social_links:
- { platform: github,         user_url: "https://github.com/doomed51" }
- { platform: x,              user_url: "https://x.com/inSenCite" }