#remote_theme: minima #pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Rachit's Catalogue

author: 
 name: Rachit S.

description: > 
  A personal site to keep track of ideas and refine them over time. Posts start as drafts and remain WIP forever. 

# theme: minima
remote_theme: jekyll/minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# link only to specific pages in the header 
header_pages:
  - index.md
  - about.md

jekyll-archives:
  enabled:
    - tags
  layouts: 
    tag: tag_archive 
  permalinks:
    tag: '/tags/:name/'

minima: 
  skin: auto

  social_links:
    - { platform: github, user_url: "https://github.com/doomed51" }
    - { platform: x, user_url: "https://x.com/inSenCite" }

