#remote_theme: minima #pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Tech, Trading, and Business Systems

author: 
 name: Rachit S.

description:  📊 Business Systems |  📈 Trading |  📚 Emerging Tech | Everything here is perpetually in beta - just like me.

# theme: minima
remote_theme: jekyll/minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# link only to specific pages in the header 
header_pages:
  - index.md
  - about.md
  - archives.html

minima: 
  skin: auto

  social_links:
    - { platform: github, user_url: "https://github.com/doomed51" }
    - { platform: x, user_url: "https://x.com/inSenCite" }
    - { platform: bmc, user_url: "https://buymeacoffee.com/rachitshankar" }

